name: Build and Release Personal AI Agent (macOS)

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering

env:
  PYTHON_VERSION: '3.11'

permissions:
  contents: write
  actions: read
  
jobs:
  build-and-release-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: Install system dependencies
      run: |
        # Install only essential system packages - we use native hdiutil for DMG creation
        echo "Using native macOS tools - no additional system packages needed"
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        # Install build tools first with extended timeout
        pip install --timeout 600 --retries 5 pyinstaller pillow
        
    - name: Install heavy ML dependencies
      run: |
        # Install the heaviest dependencies separately with extended timeout
        pip install --timeout 900 --retries 5 llama-cpp-python==0.3.9
        pip install --timeout 600 --retries 5 faiss-cpu==1.11.0
        pip install --timeout 600 --retries 5 sentence-transformers==4.1.0
        
    - name: Install remaining dependencies  
      run: |
        # Install remaining lighter dependencies
        pip install --timeout 300 --retries 3 -r requirements.txt
        
    - name: Build macOS app bundle and DMG
      run: |
        echo "🚀 Building Personal AI Agent Enhanced DMG for macOS..."
        echo "Python version: $(python --version)"
        echo "Current directory: $(pwd)"
        echo "Available files:"
        ls -la
        echo "Starting build process..."
        python build_executable.py --platform darwin --dmg
        echo "Build completed. Checking outputs..."
        
    - name: Verify build artifacts
      run: |
        echo "📋 Verifying build artifacts..."
        ls -la dist/
        # Verify app bundle exists
        if [ ! -d "dist/Personal AI Agent.app" ]; then
          echo "❌ Error: App bundle not created"
          exit 1
        fi
        echo "✅ App bundle created successfully"
        
        # Verify DMG exists  
        if [ ! -f "dist/Personal AI Agent Installer.dmg" ]; then
          echo "❌ Error: DMG not created"
          exit 1
        fi
        echo "✅ DMG created successfully"
        
    - name: Create ZIP archive for compatibility
      run: |
        cd dist
        echo "📦 Creating ZIP archive for compatibility..."
        # Create ZIP version for backward compatibility
        zip -r "PersonalAIAgent-macos-no-models.zip" "Personal AI Agent.app" "README.md" "install.py"
        echo "✅ ZIP archive created"
        ls -la *.zip *.dmg
        
    - name: Get release version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=v$(date +'%Y.%m.%d')-dev" >> $GITHUB_OUTPUT
        fi
        echo "Release version: ${{ steps.version.outputs.VERSION }}"
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ steps.version.outputs.VERSION }}
        name: Personal AI Agent ${{ steps.version.outputs.VERSION }} (macOS)
        make_latest: true
        generate_release_notes: false
        body: |
          # Personal AI Agent ${{ steps.version.outputs.VERSION }} - macOS Release
          
          ## 🍎 Enhanced macOS Experience
          - **Professional .app bundle** with proper macOS integration
          - **DMG installer** with drag-and-drop interface
          - **First-run setup** with guided Phi-2 model download (~1.7GB)
          - **Complete privacy** - all AI processing happens locally
          - **Native macOS dialogs** and proper app directory structure
          
          ## 📦 Downloads
          
          ### macOS (Only Platform Supported)
          - **Personal AI Agent Installer.dmg** - Professional macOS installer (Recommended)
          - **PersonalAIAgent-macos-no-models.zip** - ZIP version for compatibility
          
          ## 🛠️ Installation
          
          ### Enhanced DMG Installation (Recommended)
          1. Download `Personal AI Agent Installer.dmg`
          2. Double-click to mount the installer
          3. Drag "Personal AI Agent.app" to Applications folder
          4. Launch from Applications
          5. First run will show native setup dialog and download Phi-2 model (~1.7GB)
          6. Browser opens automatically to http://localhost:8000
          
          ### ZIP Installation (Alternative)
          1. Download and extract `PersonalAIAgent-macos-no-models.zip`
          2. Run `install.py` to setup environment
          3. Double-click "Personal AI Agent.app" to start
          4. First run downloads AI models automatically
          
          ## ⚙️ System Requirements
          - **macOS**: 10.14+ (Intel/Apple Silicon)
          - **RAM**: 8GB minimum, 16GB recommended
          - **Storage**: 15GB free space (for models and data)
          
          ## 🔒 Privacy & Security
          - All AI processing happens locally using Phi-2 model
          - No data sent to external AI services
          - Your documents and emails stay on your device
          - Optional Gmail integration (OAuth2, local caching only)
          
          ## 🚀 What's Included
          - Enhanced macOS .app bundle with proper Info.plist
          - Professional DMG with custom layout and Quick Start Guide
          - Progressive Phi-2 model download system
          - Native first-run experience with macOS dialogs
          - Automatic browser opening after setup
          
          ---
          
          **Platform Focus**: This release supports macOS only. Windows and Linux support planned for Q2 2025.
          
          **Full Changelog**: https://github.com/gitKnowsMe/PersonalAIAgent_backend/commits/${{ steps.version.outputs.VERSION }}
        draft: false
        prerelease: false
        files: |
          dist/Personal AI Agent Installer.dmg
          dist/PersonalAIAgent-macos-no-models.zip
          dist/README.md